config/routes.rb
TrelloVideo::Application.routes.draw do
  root to: "static_pages#root"
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  
  namespace :api, defaults: { format: :json } do
    resources :boards, except: [:new, :edit]
    resources :lists, only: [:create, :update, :destroy]
    resources :cards, only: [:create, :show, :update, :destroy]
    resources :checklists, only: [:create, :show, :update, :destroy]
    resources :items, only: [:create, :update, :show, :destroy]
    resources :board_memberships, only: [:create, :show, :destroy]
  end
end

app/models/board.rb
class Board < ActiveRecord::Base
  validates :title, :user, presence: true
  belongs_to :user
  #association lists are deleted when owner board is deleted 
  has_many :board_memberships, dependent: :destroy
  has_many :lists, dependent: :destroy
  has_many :members, through: :board_memberships, source: :user
end

app/models/board_membership.rb
class BoardMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :board
end

app/models/card.rb
class Card < ActiveRecord::Base
    validates :title, presence: true
    belongs_to :list
    #association lists are deleted when owner board is deleted 
    has_many :checklists, dependent: :destroy
end

app/models/card_assignment.rb
class CardAssignment < ActiveRecord::Base
end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :card
  has_many :items, dependent: :destroy 
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :checklist
end

app/models/list.rb
class List < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :board

  has_many :cards, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :session_token, presence: true
  validates :password, length: {minimum: 5, allow_nil: true}
  validates :email, uniqueness: true
  
  has_many :boards
  has_many :board_memberships
  attr_reader :password
  after_initialize :ensure_session_token
  
  def self.find_by_credentials(user_params)
    user = User.find_by_email(user_params[:email])
    user.try(:is_password?, user_params[:password]) ? user : nil
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end
  
  # def all_boards
  #   Board.joins(:board_memberships)
  #         .where(
  #         "boards.user_id = :user_id OR board_memberships.user_id = :user_id",
  #         {user_id: self.id})
  # end
  
  private
  
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  before_action :require_signed_in
  #need to check board's membership later
  def require_board_member!
    redirect_to new_session_url unless current_board.is_member?(current_user)
  end
end

app/controllers/api/cards_controller.rb
class Api::CardsController < Api::ApiController
  # before_action :require_board_member!
   def create
     @card = current_list.cards.new(card_params)

     if @card.save
       render json: @card
     else
       render json: @card.errors.full_messages, status: :unprocessable_entity
     end
   end
   
   def destroy
     @card = Card.find(params[:id])
     @card.destroy
     render json: {}
   end

   def update
     @card = Card.find(params[:id])
     if @card.update_attributes(card_params)
       render json: @card
     else
       render json: @card.errors.full_messages,
              status: :unprocessable_entity
     end
   end

   def show
     @card = Card.find(params[:id])
     render :show
   end

   private

   def current_list
     if params[:id]
       @card = Card.find(params[:id])
       @list = @card.list
     elsif params[:card]
       @list = List.find(params[:card][:list_id])
     end
   end

   def current_board
     current_list.board
   end

   def card_params
     params.require(:card).permit(:title, :list_id, :ord)
   end
end

app/controllers/api/items_controller.rb
class Api::ItemsController < Api::ApiController
   def create
     @items = current_checklist.items.new(item_params)
     if @items.save
       render json: @items
     else
       render json: @items.errors.full_messages, status: :unprocessable_entity
     end
   end
   
   def update
     @item = Item.find(params[:id])

     if @item.update(item_params)
       render json: @item
     else
       render json: @item.errors.full_messages, status: :unprocessable_entity
     end
   end
   
   def show
     @item = Item.find(params[:id])
     render :show
   end

   def destroy
     @item = Item.find(params[:id])
     @item.destroy
     render json: { message: 'destroyed!' }
   end

   private
   def current_checklist
     if params[:id]
       @item = Item.find(params[:id])
       @checklist = @item.checklist
     elsif params[:item]
       @checklist = Checklist.find(params[:item][:checklist_id])
     end
   end
   
   def current_card
     current_list.card
   end
   
   def current_list
     current_card.list
   end

   def current_board
     current_list.board
   end
   def item_params
     params.require(:item).permit(:done, :title, :ord, :checklist_id)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :signed_in?
  
  private
  
  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end
  
  def signed_in?
    !!current_user
  end
  
  def sign_in!(user)
    @current_user = user
    session[:token] = user.reset_token!
  end
  
  def sign_out!
    current_user.try(:reset_token!)
    session[:token] = nil
  end
  
  def require_signed_in
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by_credentials(params[:user])
    if @user
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid email and/or password"]
      render :new
    end
  end
  
  def destroy
    sign_out!
    redirect_to new_session_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_signed_in
  def root 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    "<input
        type=\"hidden\"
        name=\"authenticity_token\"
        value=\"#{ form_authenticity_token }\">".html_safe
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_content.html.erb
  <% if signed_in? %>
  <% else %>
    <div class="jumbotron row" id="introduction">
      <div class="col-xs-12 title">
        TacticBoard makes it easy to organize anything with players.
      </div><br>
      <div class="col-xs-8 col-xs-offset-2">
        <section>
    Drop the lengthy email threads, out-of-date spreadsheets, no-longer-so-sticky notes, and clunky software for managing your projects and get Trello, the easy, free, and visual way to organize your important stuff.
        </section><br>
        
        <div class="col-xs-6 col-xs-offset-3">
          <p><a href="" class="btn btn-primary btn-lg" role="button">Sign Up-It's Free</a>
          </p>
        </div>
      </div>
      
    </div>
    
    <!-- <div class="row" id="board_guidiance">
      <div class="col-xs-12 title">Trello makes it easy to organize anything with anyone.</div>

      <div class="col-xs-8 col-xs-offset-2">
        <section>
    Drop the lengthy email threads, out-of-date spreadsheets, no-longer-so-sticky notes, and clunky software for managing your projects and get Trello, the easy, free, and visual way to organize your important stuff.
        </section>
      </div>

    </div>

    <div class="row" id="introduction_footer">
      <div class="col-xs-12 title">Trello makes it easy to organize anything with anyone.</div>

      <div class="col-xs-8 col-xs-offset-2">
        <section>
    Drop the lengthy email threads, out-of-date spreadsheets, no-longer-so-sticky notes, and clunky software for managing your projects and get Trello, the easy, free, and visual way to organize your important stuff.
        </section>
      </div>

    </div> -->
    
    
  <% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
<div class="container-fluid">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">TacticBoard</a>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
    <% if signed_in? %>
      <li>
        <%= button_to "Sign out", session_url, method: :delete, class: "btn btn-primary navbar-btn" %>
      </li>
    <% else %>
      <li><%= link_to "Log in", new_session_url %></li>
      <li><%= link_to "Sign up", new_user_url %></li>
    <% end %>
    </ul>
  </div>
</div>
</nav>

<% if flash[:errors] %>
<div class="alert alert-warning alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
<%= flash[:errors].join("<br>").html_safe %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TacticBoard</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "layouts/header" %>
  <%= yield %>
  <%=render partial: "layouts/content"%>
</body>
</html>